defaults:
  - _self_
  - aml_config
  - aoai_config

zeroorfewshot_config:
  pipeline:
    base_experiment_name: gsm8k_zeroorfewshot_debugging
    tags:
    default_compute_target: isolatedcompute
  json_guidance_programs:
    - gsm8k_zero_or_few_shot_plain.py
    - gsm8k_zero_or_few_shot_regex_number.py
    - gsm8k_zero_or_few_shot_basic_json.py
    - gsm8k_zero_or_few_shot_json_response.py
  llamacpp_config:
    compute_target: gput4
  random_seed: 4521
  n_samples: 1